### ISSUE TITLE
Still the case?

### ISSUE THREAD

**Issue by ghost** [Syniurge/i2c-amd-mp2#10] opened 2019-04-17 19:22 UTC
Hi

Is this still required or has it been included with the kernel by now? I'm interested in buying an amd Lenovo yoga 530.

Thanks!

**Comment by splav** [comment] 2019-04-17 20:42
It should be in 5.2. Already merged in i2c subsystem tree. See closed issue.

P.S. @Syniurge may be the issue should be kept open until 5.2 release or at least 5.2-rc1? I suspect there will be more people asking same thing.
P.P.S. dkms is pretty easy in use. It's just done once - no manual operations during kernel update.

**Comment by ghost** [comment] 2019-04-23 11:15
Okay, thanks!

**Comment by GaryGate15** [comment] 2019-07-01 08:27
This works nicely on my Ideapad 530S-ARR and kernel 4.18
I have tried to upgrade to 4.19, the tap-to-click stops working after about 5 minutes. Same with kernels 5.0 and 5.1 
Maybe it will be ok with kernel 5.2?

**Comment by Syniurge** [comment] 2019-07-01 15:56
@GaryGate15 I have a similar issue with my Yoga, tap-to-click "randomly" stops working after between 5 to 30 mins, but although this may deserve more investigation it feels more likely that the problem isn't caused by the MP2 I2C controller driver. Other touchpad users experience this, so the issue may be from X, libinput or KDE, and a possibility is that our touchpad model* might send a peculiar HID report that triggers a bug of one of those layers.

As a workaround if I switch to text mode with `CTRL+ALT+F6` and go back to X with `ALT+right arrow` then tap-to-click gets restored.

To debug this, one has to look into how libinput and its clients handle touchpads. It's not really high priority for me right now but if more people are affected and provide me information about their environments this would probably help with the investigation.

[*]: The "reported model" of Yoga 530's HID touchpad:
```bash
$ xinput
⎜   ↳ MSFT0001:00 06CB:7F27 Touchpad            id=17   [slave  pointer  (2)]
```

**Comment by GaryGate15** [comment] 2019-07-01 20:56
@Syniurge   I would be ready to help. What kind of environment information is needed?
My touchpad is :
` ↳ MSFT0001:00 04F3:304B Touchpad          	id=12	[slave  pointer  (2)]`

**Comment by Syniurge** [comment] 2019-08-03 22:33
5.2 has been out for a while, although it's still rough on my laptop and others' (https://bugs.freedesktop.org/show_bug.cgi?id=111122).

**Closed as completed by Syniurge** 2019-08-03 22:33 UTC
